# Generated by Django 3.2.8 on 2021-11-04 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_appointments', '0002_auto_20211025_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_provider', models.SmallIntegerField()),
                ('id_section', models.CharField(choices=[('SECTION_ONE', 'section one'), ('SECTION_tWO', 'section two'), ('SECTION_THREE', 'section three')], max_length=100)),
                ('configurations', models.JSONField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='RolesUser',
        ),
    ]
